// blockly-svelte/src/components/BlocklyComponent.svelte
<script>
  import { onMount } from "svelte";
  import Blockly from "blockly";

  onMount(() => {
    this.workspace = Blockly.inject(document.getElementById("blocklyDiv"), {
      toolbox: document.getElementById("toolbox")
    });
  });
</script>

<style scoped>
  #blocklyDiv {
    height: 100%;
    width: 100%;
    position: absolute;
    bottom: 0;
    text-align: left;
  }
</style>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<div>
  <div id="blocklyDiv" />
  <xml id="toolbox" style="display:none">
    <slot />
  </xml>
</div>

// examples/blockly-vue3/src/components/BlocklyComponent.vue
<script setup>
/**
 * @fileoverview Blockly Vue Component.
 * @author dcoodien@gmail.com (Dylan Coodien)
 */

import { onMounted, ref, shallowRef } from "vue";
import Blockly from "blockly";

const props = defineProps(["options"]);
const blocklyToolbox = ref();
const blocklyDiv = ref();
const workspace = shallowRef();

defineExpose({ workspace });

onMounted(() => {
  const options = props.options || {};
  if (!options.toolbox) {
    options.toolbox = blocklyToolbox.value;
  }
  workspace.value = Blockly.inject(blocklyDiv.value, options);
});
</script>

<template>
  <div>
    <div class="blocklyDiv" ref="blocklyDiv"></div>
    <xml ref="blocklyToolbox" style="display: none">
      <slot></slot>
    </xml>
  </div>
</template>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.blocklyDiv {
  height: 100%;
  width: 100%;
  text-align: left;
}
</style>
